CREATE TABLE IF NOT EXISTS pending_replies (
    tg_message_id INTEGER PRIMARY KEY,
    tt_user_id INTEGER NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
